ALTER TABLE turnos
    ADD COLUMN IF NOT EXISTS modo_demo TINYINT(1) NOT NULL DEFAULT 0 AFTER fim_em;

ALTER TABLE turnos_especiais
    ADD COLUMN IF NOT EXISTS modo_demo TINYINT(1) NOT NULL DEFAULT 0 AFTER fim_em;
